### ISSUE TITLE
annonfile link expired

### ISSUE THREAD

**Issue by 404b** [Summaw/Text-Captcha-Solver#2]

**Comment by Summaw** [comment]
I just uploaded again to anonfile, try now 👍

**Comment by 404b** [comment]
> I just uploaded again to anonfile, try now 👍

![image](https://user-images.githubusercontent.com/38348819/217573174-5c347a99-f622-41a1-a9b3-f80e71307a7f.png)

**Comment by 404b** [comment]
you can try on this https://pixeldrain.com/

**Comment by Summaw** [comment]
Thanks, Will update resp with new link now.
