### ISSUE TITLE
ModuleNotFoundError: No module named 'object_detection'

### ISSUE THREAD

**Issue by 404b** [Summaw/Text-Captcha-Solver#3]
x python .\solver.py
Traceback (most recent call last):
  File "D:\textCaptcha\Text-Captcha-Solver\solver.py", line 1, in <module>
    from captcha_detector import Captcha_detection
  File "D:\textCaptcha\Text-Captcha-Solver\captcha_detector.py", line 17, in <module>
    from object_detection.utils import ops as utils_ops
ModuleNotFoundError: No module named 'object_detection'

**Comment by Summaw** [comment]
You need to use python3. if that still does not work try ```pip install tensorflow-object-detection-api```

**Comment by 404b** [comment]
Python 3.9.13

` python .\solver.py    `       
               
```
Traceback (most recent call last):
  File "D:\textCaptcha\Text-Captcha-Solver\solver.py", line 1, in <module>
    from captcha_detector import Captcha_detection
  File "D:\textCaptcha\Text-Captcha-Solver\captcha_detector.py", line 28, in <module>
    label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
  File "C:\Users\pc\AppData\Roaming\Python\Python39\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap
    with tf.gfile.GFile(path, 'r') as fid:
AttributeError: module 'tensorflow' has no attribute 'gfile'
```

**Comment by 404b** [comment]
> pip3.exe install tensorflow-object-detection-api

        * after installing this


> pip3.exe install object-detection 


 
```
Traceback (most recent call last):
  File "D:\textCaptcha\Text-Captcha-Solver\solver.py", line 1, in <module>
    from captcha_detector import Captcha_detection
  File "D:\textCaptcha\Text-Captcha-Solver\captcha_detector.py", line 17, in <module>
    from object_detection.utils import ops as utils_ops
ModuleNotFoundError: No module named 'object_detection.utils'

```

**Comment by Summaw** [comment]
> Python 3.9.13
> 
> `python .\solver.py `
> 
> ```
> Traceback (most recent call last):
>   File "D:\textCaptcha\Text-Captcha-Solver\solver.py", line 1, in <module>
>     from captcha_detector import Captcha_detection
>   File "D:\textCaptcha\Text-Captcha-Solver\captcha_detector.py", line 28, in <module>
>     label_map = label_map_util.load_labelmap(PATH_TO_LABELS)
>   File "C:\Users\pc\AppData\Roaming\Python\Python39\site-packages\object_detection\utils\label_map_util.py", line 132, in load_labelmap
>     with tf.gfile.GFile(path, 'r') as fid:
> AttributeError: module 'tensorflow' has no attribute 'gfile'
> ```

Go back to when you recieve this error. Here is the fix:
Okay, please go to this file ```C:\Users\pc\AppData\Roaming\Python\Python39\site-packages\object_detection\utils\label_map_util.py```, From there CTRL + F in the file and search for ```tf.gfile.GFile```, next you will need to replace all apperences of ```tf.gfile.GFile``` to ```tf.io.gfile.GFile```
