### ISSUE TITLE
how to use it in chrome for captcha website 

### ISSUE THREAD

**Issue by betagoyal** [Summaw/Text-Captcha-Solver#4]
Thanks for making this type of project . But new person like me dont know how to use it . So pls make it available for everyone . and give some detail for how to use .

**Comment by Summaw** [comment]
> Thanks for making this type of project . But new person like me dont know how to use it . So pls make it available for everyone . and give some detail for how to use .

Hello there, As I mentioned in the readme file, you will need to train a model to work with the website you would like the solver to work for. Now once you have trained a model to work with captcha the site is providing you can query the selector on the page where the image is stored and either take a screenshot of the image and have your program automatically save it to a folder where you can then tell the solver to open and get the letters/numbers provided, or you can just have your program upload the url to the local host server I have created for you as an example in in the examples folder. You will need to make adjustments to both your program and probably the server example as well to work for what you need it to.
