### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by guinaatz** [Summaw/Text-Captcha-Solver#7]
Hello, I play a game that every time it sends me a captcha, would it be possible to solve it and respond? It's a web game I'm trying but I don't think I have the knowledge yet, could you help me? https://uploaddeimagens.com.br/imagens/YbG2oRQ

**Comment by Summaw** [comment]
Hey, Yes this is possible you will need to train your own model.
You can learn how to do this here [https://github.com/Summaw/Text-Captcha-Solver/blob/main/README.md#program-for-photos](README.md)

**Comment by guinaatz** [comment]
ok i go try

**Comment by guinaatz** [comment]
Unfortunately I couldn't, you can help me? I think it's something quick for you

**Comment by Summaw** [comment]
> Unfortunately I couldn't, you can help me? I think it's something quick for you

What could you not figure out? You followed instructions from the https://github.com/heartexlabs/labelImg right?

**Comment by guinaatz** [comment]
Yes, I followed, but I'm trying to implement it in a game to make it automatic and respond to this, which I haven't been able to do.

**Comment by guinaatz** [comment]
I'm trying to develop something like this,
   /*solvingCaptcha = true;

         const backgroundImageStyle = document.querySelector("#captcha_form_content #captcha_img_div").style.backgroundImage;
         const regex = /url\("(?<base64>data:image\/jpeg\;base64.+)\"\)/m;

         const matches = backgroundImageStyle.match(regex);

         if (!matches) {
             solvingCaptcha = false;
             return;
         }

         const solution = await solveCaptcha(matches.groups.base64).catch(e => {
             solvingCaptcha = false;
         });

         // Type captcha and submit
         document.getElementById("captcha_input").value = solution;
         Captcha.submit();

         solvingCaptcha = false;*/
     }
}, 2000);

const solveCaptcha = async (base64) => new Promise((resolve, reject) => {
     let xhr = new XMLHttpRequest();
     xhr.open("POST", "http://localhost:3000/tasks", true);
     xhr.setRequestHeader('Content-Type', 'application/json');
     xhr.send(JSON.stringify({
         img: base64,
         token: ""
     }));

     xhr.onload = function async() {
         let data = JSON.parse(this.responseText);

         setTimeout(async () => {
             let xhr = new XMLHttpRequest();
             xhr.open("POST", `http://localhost:3000/result/${data.taskId}`, true);
             xhr.setRequestHeader('Content-Type', 'application/json');
             xhr.send(JSON.stringify({
                 token: ""
             }));

             xhr.onload = function async() {
                 const data = JSON.parse(xhr.responseText);
                 solvingCaptcha = false;
                 resolve(data.solution);
             }
         }, 20000);
     }
});

**Comment by guinaatz** [comment]
but I can't even run your system

**Comment by Summaw** [comment]
> I'm trying to develop something like this, /*solvingCaptcha = true;
> 
> ```
>      const backgroundImageStyle = document.querySelector("#captcha_form_content #captcha_img_div").style.backgroundImage;
>      const regex = /url\("(?<base64>data:image\/jpeg\;base64.+)\"\)/m;
> 
>      const matches = backgroundImageStyle.match(regex);
> 
>      if (!matches) {
>          solvingCaptcha = false;
>          return;
>      }
> 
>      const solution = await solveCaptcha(matches.groups.base64).catch(e => {
>          solvingCaptcha = false;
>      });
> 
>      // Type captcha and submit
>      document.getElementById("captcha_input").value = solution;
>      Captcha.submit();
> 
>      solvingCaptcha = false;*/
>  }
> ```
> 
> }, 2000);
> 
> const solveCaptcha = async (base64) => new Promise((resolve, reject) => { let xhr = new XMLHttpRequest(); xhr.open("POST", "http://localhost:3000/tasks", true); xhr.setRequestHeader('Content-Type', 'application/json'); xhr.send(JSON.stringify({ img: base64, token: "" }));
> 
> ```
>  xhr.onload = function async() {
>      let data = JSON.parse(this.responseText);
> 
>      setTimeout(async () => {
>          let xhr = new XMLHttpRequest();
>          xhr.open("POST", `http://localhost:3000/result/${data.taskId}`, true);
>          xhr.setRequestHeader('Content-Type', 'application/json');
>          xhr.send(JSON.stringify({
>              token: ""
>          }));
> 
>          xhr.onload = function async() {
>              const data = JSON.parse(xhr.responseText);
>              solvingCaptcha = false;
>              resolve(data.solution);
>          }
>      }, 20000);
>  }
> ```
> 
> });

Are you sure that this is returning the correct image?

**Comment by Summaw** [comment]
And what isn't running correctly?

**Comment by guinaatz** [comment]
I can't actually create the server to send the image, it doesn't seem to run

**Comment by Summaw** [comment]
> I can't actually create the server to send the image, it doesn't seem to run

Sorry just seeing this I have been away, can you please send me screen prints of the error message that is returned when you try to start the server? I need more information regarding your problem for me to be able to help you.
